// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Friendships      string
	GroupUsers       string
	Groups           string
	SchemaMigrations string
	Users            string
}{
	Friendships:      "friendships",
	GroupUsers:       "group_users",
	Groups:           "groups",
	SchemaMigrations: "schema_migrations",
	Users:            "users",
}
