// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"strconv"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/strmangle"
)

// M type is for providing columns and column values to UpdateAll.
type M map[string]interface{}

// ErrSyncFail occurs during insert when the record could not be retrieved in
// order to populate default value information. This usually happens when LastInsertId
// fails or there was a primary key configuration that was not resolvable.
var ErrSyncFail = errors.New("models: failed to synchronize data after insert")

type insertCache struct {
	query        string
	retQuery     string
	valueMapping []uint64
	retMapping   []uint64
}

type updateCache struct {
	query        string
	valueMapping []uint64
}

func makeCacheKey(cols boil.Columns, nzDefaults []string) string {
	buf := strmangle.GetBuffer()

	buf.WriteString(strconv.Itoa(cols.Kind))
	for _, w := range cols.Cols {
		buf.WriteString(w)
	}

	if len(nzDefaults) != 0 {
		buf.WriteByte('.')
	}
	for _, nz := range nzDefaults {
		buf.WriteString(nz)
	}

	str := buf.String()
	strmangle.PutBuffer(buf)
	return str
}

type FriendshipsWorkflowState string

// Enum values for FriendshipsWorkflowState
const (
	FriendshipsWorkflowStatePending   FriendshipsWorkflowState = "pending"
	FriendshipsWorkflowStateActive    FriendshipsWorkflowState = "active"
	FriendshipsWorkflowStateRejected  FriendshipsWorkflowState = "rejected"
	FriendshipsWorkflowStateCancelled FriendshipsWorkflowState = "cancelled"
)

func AllFriendshipsWorkflowState() []FriendshipsWorkflowState {
	return []FriendshipsWorkflowState{
		FriendshipsWorkflowStatePending,
		FriendshipsWorkflowStateActive,
		FriendshipsWorkflowStateRejected,
		FriendshipsWorkflowStateCancelled,
	}
}

func (e FriendshipsWorkflowState) IsValid() error {
	switch e {
	case FriendshipsWorkflowStatePending, FriendshipsWorkflowStateActive, FriendshipsWorkflowStateRejected, FriendshipsWorkflowStateCancelled:
		return nil
	default:
		return errors.New("enum is not valid")
	}
}

func (e FriendshipsWorkflowState) String() string {
	return string(e)
}

func (e FriendshipsWorkflowState) Ordinal() int {
	switch e {
	case FriendshipsWorkflowStatePending:
		return 0
	case FriendshipsWorkflowStateActive:
		return 1
	case FriendshipsWorkflowStateRejected:
		return 2
	case FriendshipsWorkflowStateCancelled:
		return 3

	default:
		panic(errors.New("enum is not valid"))
	}
}

type GroupUsersWorkflowState string

// Enum values for GroupUsersWorkflowState
const (
	GroupUsersWorkflowStatePending   GroupUsersWorkflowState = "pending"
	GroupUsersWorkflowStateActive    GroupUsersWorkflowState = "active"
	GroupUsersWorkflowStateRejected  GroupUsersWorkflowState = "rejected"
	GroupUsersWorkflowStateCancelled GroupUsersWorkflowState = "cancelled"
)

func AllGroupUsersWorkflowState() []GroupUsersWorkflowState {
	return []GroupUsersWorkflowState{
		GroupUsersWorkflowStatePending,
		GroupUsersWorkflowStateActive,
		GroupUsersWorkflowStateRejected,
		GroupUsersWorkflowStateCancelled,
	}
}

func (e GroupUsersWorkflowState) IsValid() error {
	switch e {
	case GroupUsersWorkflowStatePending, GroupUsersWorkflowStateActive, GroupUsersWorkflowStateRejected, GroupUsersWorkflowStateCancelled:
		return nil
	default:
		return errors.New("enum is not valid")
	}
}

func (e GroupUsersWorkflowState) String() string {
	return string(e)
}

func (e GroupUsersWorkflowState) Ordinal() int {
	switch e {
	case GroupUsersWorkflowStatePending:
		return 0
	case GroupUsersWorkflowStateActive:
		return 1
	case GroupUsersWorkflowStateRejected:
		return 2
	case GroupUsersWorkflowStateCancelled:
		return 3

	default:
		panic(errors.New("enum is not valid"))
	}
}

type GroupsWorkflowState string

// Enum values for GroupsWorkflowState
const (
	GroupsWorkflowStateActive  GroupsWorkflowState = "active"
	GroupsWorkflowStateDeleted GroupsWorkflowState = "deleted"
)

func AllGroupsWorkflowState() []GroupsWorkflowState {
	return []GroupsWorkflowState{
		GroupsWorkflowStateActive,
		GroupsWorkflowStateDeleted,
	}
}

func (e GroupsWorkflowState) IsValid() error {
	switch e {
	case GroupsWorkflowStateActive, GroupsWorkflowStateDeleted:
		return nil
	default:
		return errors.New("enum is not valid")
	}
}

func (e GroupsWorkflowState) String() string {
	return string(e)
}

func (e GroupsWorkflowState) Ordinal() int {
	switch e {
	case GroupsWorkflowStateActive:
		return 0
	case GroupsWorkflowStateDeleted:
		return 1

	default:
		panic(errors.New("enum is not valid"))
	}
}

type GroupsType string

// Enum values for GroupsType
const (
	GroupsTypePrivate GroupsType = "private"
	GroupsTypePublic  GroupsType = "public"
)

func AllGroupsType() []GroupsType {
	return []GroupsType{
		GroupsTypePrivate,
		GroupsTypePublic,
	}
}

func (e GroupsType) IsValid() error {
	switch e {
	case GroupsTypePrivate, GroupsTypePublic:
		return nil
	default:
		return errors.New("enum is not valid")
	}
}

func (e GroupsType) String() string {
	return string(e)
}

func (e GroupsType) Ordinal() int {
	switch e {
	case GroupsTypePrivate:
		return 0
	case GroupsTypePublic:
		return 1

	default:
		panic(errors.New("enum is not valid"))
	}
}

type UsersWorkflowState string

// Enum values for UsersWorkflowState
const (
	UsersWorkflowStateActive    UsersWorkflowState = "active"
	UsersWorkflowStateSuspended UsersWorkflowState = "suspended"
	UsersWorkflowStateDeleted   UsersWorkflowState = "deleted"
)

func AllUsersWorkflowState() []UsersWorkflowState {
	return []UsersWorkflowState{
		UsersWorkflowStateActive,
		UsersWorkflowStateSuspended,
		UsersWorkflowStateDeleted,
	}
}

func (e UsersWorkflowState) IsValid() error {
	switch e {
	case UsersWorkflowStateActive, UsersWorkflowStateSuspended, UsersWorkflowStateDeleted:
		return nil
	default:
		return errors.New("enum is not valid")
	}
}

func (e UsersWorkflowState) String() string {
	return string(e)
}

func (e UsersWorkflowState) Ordinal() int {
	switch e {
	case UsersWorkflowStateActive:
		return 0
	case UsersWorkflowStateSuspended:
		return 1
	case UsersWorkflowStateDeleted:
		return 2

	default:
		panic(errors.New("enum is not valid"))
	}
}
