// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Chatrooms        string
	Friendships      string
	SchemaMigrations string
	Users            string
}{
	Chatrooms:        "chatrooms",
	Friendships:      "friendships",
	SchemaMigrations: "schema_migrations",
	Users:            "users",
}
