// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// GroupUser is an object representing the database table.
type GroupUser struct {
	ID                  int64                   `boil:"id" json:"id" toml:"id" yaml:"id"`
	GroupID             int64                   `boil:"group_id" json:"group_id" toml:"group_id" yaml:"group_id"`
	RequesterID         int64                   `boil:"requester_id" json:"requester_id" toml:"requester_id" yaml:"requester_id"`
	UserID              int64                   `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	WorkflowState       GroupUsersWorkflowState `boil:"workflow_state" json:"workflow_state" toml:"workflow_state" yaml:"workflow_state"`
	WorkflowCompletedBy int64                   `boil:"workflow_completed_by" json:"workflow_completed_by" toml:"workflow_completed_by" yaml:"workflow_completed_by"`
	CreatedAt           time.Time               `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt           time.Time               `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	DeletedAt           null.Time               `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`

	R *groupUserR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L groupUserL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var GroupUserColumns = struct {
	ID                  string
	GroupID             string
	RequesterID         string
	UserID              string
	WorkflowState       string
	WorkflowCompletedBy string
	CreatedAt           string
	UpdatedAt           string
	DeletedAt           string
}{
	ID:                  "id",
	GroupID:             "group_id",
	RequesterID:         "requester_id",
	UserID:              "user_id",
	WorkflowState:       "workflow_state",
	WorkflowCompletedBy: "workflow_completed_by",
	CreatedAt:           "created_at",
	UpdatedAt:           "updated_at",
	DeletedAt:           "deleted_at",
}

var GroupUserTableColumns = struct {
	ID                  string
	GroupID             string
	RequesterID         string
	UserID              string
	WorkflowState       string
	WorkflowCompletedBy string
	CreatedAt           string
	UpdatedAt           string
	DeletedAt           string
}{
	ID:                  "group_users.id",
	GroupID:             "group_users.group_id",
	RequesterID:         "group_users.requester_id",
	UserID:              "group_users.user_id",
	WorkflowState:       "group_users.workflow_state",
	WorkflowCompletedBy: "group_users.workflow_completed_by",
	CreatedAt:           "group_users.created_at",
	UpdatedAt:           "group_users.updated_at",
	DeletedAt:           "group_users.deleted_at",
}

// Generated where

type whereHelperGroupUsersWorkflowState struct{ field string }

func (w whereHelperGroupUsersWorkflowState) EQ(x GroupUsersWorkflowState) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelperGroupUsersWorkflowState) NEQ(x GroupUsersWorkflowState) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelperGroupUsersWorkflowState) LT(x GroupUsersWorkflowState) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelperGroupUsersWorkflowState) LTE(x GroupUsersWorkflowState) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelperGroupUsersWorkflowState) GT(x GroupUsersWorkflowState) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelperGroupUsersWorkflowState) GTE(x GroupUsersWorkflowState) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelperGroupUsersWorkflowState) IN(slice []GroupUsersWorkflowState) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperGroupUsersWorkflowState) NIN(slice []GroupUsersWorkflowState) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var GroupUserWhere = struct {
	ID                  whereHelperint64
	GroupID             whereHelperint64
	RequesterID         whereHelperint64
	UserID              whereHelperint64
	WorkflowState       whereHelperGroupUsersWorkflowState
	WorkflowCompletedBy whereHelperint64
	CreatedAt           whereHelpertime_Time
	UpdatedAt           whereHelpertime_Time
	DeletedAt           whereHelpernull_Time
}{
	ID:                  whereHelperint64{field: "\"group_users\".\"id\""},
	GroupID:             whereHelperint64{field: "\"group_users\".\"group_id\""},
	RequesterID:         whereHelperint64{field: "\"group_users\".\"requester_id\""},
	UserID:              whereHelperint64{field: "\"group_users\".\"user_id\""},
	WorkflowState:       whereHelperGroupUsersWorkflowState{field: "\"group_users\".\"workflow_state\""},
	WorkflowCompletedBy: whereHelperint64{field: "\"group_users\".\"workflow_completed_by\""},
	CreatedAt:           whereHelpertime_Time{field: "\"group_users\".\"created_at\""},
	UpdatedAt:           whereHelpertime_Time{field: "\"group_users\".\"updated_at\""},
	DeletedAt:           whereHelpernull_Time{field: "\"group_users\".\"deleted_at\""},
}

// GroupUserRels is where relationship names are stored.
var GroupUserRels = struct {
	Group                   string
	Requester               string
	User                    string
	WorkflowCompletedByUser string
}{
	Group:                   "Group",
	Requester:               "Requester",
	User:                    "User",
	WorkflowCompletedByUser: "WorkflowCompletedByUser",
}

// groupUserR is where relationships are stored.
type groupUserR struct {
	Group                   *Group `boil:"Group" json:"Group" toml:"Group" yaml:"Group"`
	Requester               *User  `boil:"Requester" json:"Requester" toml:"Requester" yaml:"Requester"`
	User                    *User  `boil:"User" json:"User" toml:"User" yaml:"User"`
	WorkflowCompletedByUser *User  `boil:"WorkflowCompletedByUser" json:"WorkflowCompletedByUser" toml:"WorkflowCompletedByUser" yaml:"WorkflowCompletedByUser"`
}

// NewStruct creates a new relationship struct
func (*groupUserR) NewStruct() *groupUserR {
	return &groupUserR{}
}

func (r *groupUserR) GetGroup() *Group {
	if r == nil {
		return nil
	}
	return r.Group
}

func (r *groupUserR) GetRequester() *User {
	if r == nil {
		return nil
	}
	return r.Requester
}

func (r *groupUserR) GetUser() *User {
	if r == nil {
		return nil
	}
	return r.User
}

func (r *groupUserR) GetWorkflowCompletedByUser() *User {
	if r == nil {
		return nil
	}
	return r.WorkflowCompletedByUser
}

// groupUserL is where Load methods for each relationship are stored.
type groupUserL struct{}

var (
	groupUserAllColumns            = []string{"id", "group_id", "requester_id", "user_id", "workflow_state", "workflow_completed_by", "created_at", "updated_at", "deleted_at"}
	groupUserColumnsWithoutDefault = []string{"id", "group_id", "requester_id", "user_id", "workflow_state", "workflow_completed_by"}
	groupUserColumnsWithDefault    = []string{"created_at", "updated_at", "deleted_at"}
	groupUserPrimaryKeyColumns     = []string{"id"}
	groupUserGeneratedColumns      = []string{}
)

type (
	// GroupUserSlice is an alias for a slice of pointers to GroupUser.
	// This should almost always be used instead of []GroupUser.
	GroupUserSlice []*GroupUser
	// GroupUserHook is the signature for custom GroupUser hook methods
	GroupUserHook func(context.Context, boil.ContextExecutor, *GroupUser) error

	groupUserQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	groupUserType                 = reflect.TypeOf(&GroupUser{})
	groupUserMapping              = queries.MakeStructMapping(groupUserType)
	groupUserPrimaryKeyMapping, _ = queries.BindMapping(groupUserType, groupUserMapping, groupUserPrimaryKeyColumns)
	groupUserInsertCacheMut       sync.RWMutex
	groupUserInsertCache          = make(map[string]insertCache)
	groupUserUpdateCacheMut       sync.RWMutex
	groupUserUpdateCache          = make(map[string]updateCache)
	groupUserUpsertCacheMut       sync.RWMutex
	groupUserUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var groupUserAfterSelectMu sync.Mutex
var groupUserAfterSelectHooks []GroupUserHook

var groupUserBeforeInsertMu sync.Mutex
var groupUserBeforeInsertHooks []GroupUserHook
var groupUserAfterInsertMu sync.Mutex
var groupUserAfterInsertHooks []GroupUserHook

var groupUserBeforeUpdateMu sync.Mutex
var groupUserBeforeUpdateHooks []GroupUserHook
var groupUserAfterUpdateMu sync.Mutex
var groupUserAfterUpdateHooks []GroupUserHook

var groupUserBeforeDeleteMu sync.Mutex
var groupUserBeforeDeleteHooks []GroupUserHook
var groupUserAfterDeleteMu sync.Mutex
var groupUserAfterDeleteHooks []GroupUserHook

var groupUserBeforeUpsertMu sync.Mutex
var groupUserBeforeUpsertHooks []GroupUserHook
var groupUserAfterUpsertMu sync.Mutex
var groupUserAfterUpsertHooks []GroupUserHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *GroupUser) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range groupUserAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *GroupUser) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range groupUserBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *GroupUser) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range groupUserAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *GroupUser) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range groupUserBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *GroupUser) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range groupUserAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *GroupUser) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range groupUserBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *GroupUser) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range groupUserAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *GroupUser) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range groupUserBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *GroupUser) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range groupUserAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddGroupUserHook registers your hook function for all future operations.
func AddGroupUserHook(hookPoint boil.HookPoint, groupUserHook GroupUserHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		groupUserAfterSelectMu.Lock()
		groupUserAfterSelectHooks = append(groupUserAfterSelectHooks, groupUserHook)
		groupUserAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		groupUserBeforeInsertMu.Lock()
		groupUserBeforeInsertHooks = append(groupUserBeforeInsertHooks, groupUserHook)
		groupUserBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		groupUserAfterInsertMu.Lock()
		groupUserAfterInsertHooks = append(groupUserAfterInsertHooks, groupUserHook)
		groupUserAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		groupUserBeforeUpdateMu.Lock()
		groupUserBeforeUpdateHooks = append(groupUserBeforeUpdateHooks, groupUserHook)
		groupUserBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		groupUserAfterUpdateMu.Lock()
		groupUserAfterUpdateHooks = append(groupUserAfterUpdateHooks, groupUserHook)
		groupUserAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		groupUserBeforeDeleteMu.Lock()
		groupUserBeforeDeleteHooks = append(groupUserBeforeDeleteHooks, groupUserHook)
		groupUserBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		groupUserAfterDeleteMu.Lock()
		groupUserAfterDeleteHooks = append(groupUserAfterDeleteHooks, groupUserHook)
		groupUserAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		groupUserBeforeUpsertMu.Lock()
		groupUserBeforeUpsertHooks = append(groupUserBeforeUpsertHooks, groupUserHook)
		groupUserBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		groupUserAfterUpsertMu.Lock()
		groupUserAfterUpsertHooks = append(groupUserAfterUpsertHooks, groupUserHook)
		groupUserAfterUpsertMu.Unlock()
	}
}

// One returns a single groupUser record from the query.
func (q groupUserQuery) One(ctx context.Context, exec boil.ContextExecutor) (*GroupUser, error) {
	o := &GroupUser{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for group_users")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all GroupUser records from the query.
func (q groupUserQuery) All(ctx context.Context, exec boil.ContextExecutor) (GroupUserSlice, error) {
	var o []*GroupUser

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to GroupUser slice")
	}

	if len(groupUserAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all GroupUser records in the query.
func (q groupUserQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count group_users rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q groupUserQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if group_users exists")
	}

	return count > 0, nil
}

// Group pointed to by the foreign key.
func (o *GroupUser) Group(mods ...qm.QueryMod) groupQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.GroupID),
	}

	queryMods = append(queryMods, mods...)

	return Groups(queryMods...)
}

// Requester pointed to by the foreign key.
func (o *GroupUser) Requester(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.RequesterID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// User pointed to by the foreign key.
func (o *GroupUser) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// WorkflowCompletedByUser pointed to by the foreign key.
func (o *GroupUser) WorkflowCompletedByUser(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.WorkflowCompletedBy),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadGroup allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (groupUserL) LoadGroup(ctx context.Context, e boil.ContextExecutor, singular bool, maybeGroupUser interface{}, mods queries.Applicator) error {
	var slice []*GroupUser
	var object *GroupUser

	if singular {
		var ok bool
		object, ok = maybeGroupUser.(*GroupUser)
		if !ok {
			object = new(GroupUser)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeGroupUser)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeGroupUser))
			}
		}
	} else {
		s, ok := maybeGroupUser.(*[]*GroupUser)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeGroupUser)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeGroupUser))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &groupUserR{}
		}
		args[object.GroupID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &groupUserR{}
			}

			args[obj.GroupID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`groups`),
		qm.WhereIn(`groups.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Group")
	}

	var resultSlice []*Group
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Group")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for groups")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for groups")
	}

	if len(groupAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Group = foreign
		if foreign.R == nil {
			foreign.R = &groupR{}
		}
		foreign.R.GroupUsers = append(foreign.R.GroupUsers, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.GroupID == foreign.ID {
				local.R.Group = foreign
				if foreign.R == nil {
					foreign.R = &groupR{}
				}
				foreign.R.GroupUsers = append(foreign.R.GroupUsers, local)
				break
			}
		}
	}

	return nil
}

// LoadRequester allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (groupUserL) LoadRequester(ctx context.Context, e boil.ContextExecutor, singular bool, maybeGroupUser interface{}, mods queries.Applicator) error {
	var slice []*GroupUser
	var object *GroupUser

	if singular {
		var ok bool
		object, ok = maybeGroupUser.(*GroupUser)
		if !ok {
			object = new(GroupUser)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeGroupUser)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeGroupUser))
			}
		}
	} else {
		s, ok := maybeGroupUser.(*[]*GroupUser)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeGroupUser)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeGroupUser))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &groupUserR{}
		}
		args[object.RequesterID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &groupUserR{}
			}

			args[obj.RequesterID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Requester = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.RequesterGroupUsers = append(foreign.R.RequesterGroupUsers, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.RequesterID == foreign.ID {
				local.R.Requester = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.RequesterGroupUsers = append(foreign.R.RequesterGroupUsers, local)
				break
			}
		}
	}

	return nil
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (groupUserL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeGroupUser interface{}, mods queries.Applicator) error {
	var slice []*GroupUser
	var object *GroupUser

	if singular {
		var ok bool
		object, ok = maybeGroupUser.(*GroupUser)
		if !ok {
			object = new(GroupUser)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeGroupUser)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeGroupUser))
			}
		}
	} else {
		s, ok := maybeGroupUser.(*[]*GroupUser)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeGroupUser)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeGroupUser))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &groupUserR{}
		}
		args[object.UserID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &groupUserR{}
			}

			args[obj.UserID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.GroupUsers = append(foreign.R.GroupUsers, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.GroupUsers = append(foreign.R.GroupUsers, local)
				break
			}
		}
	}

	return nil
}

// LoadWorkflowCompletedByUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (groupUserL) LoadWorkflowCompletedByUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeGroupUser interface{}, mods queries.Applicator) error {
	var slice []*GroupUser
	var object *GroupUser

	if singular {
		var ok bool
		object, ok = maybeGroupUser.(*GroupUser)
		if !ok {
			object = new(GroupUser)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeGroupUser)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeGroupUser))
			}
		}
	} else {
		s, ok := maybeGroupUser.(*[]*GroupUser)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeGroupUser)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeGroupUser))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &groupUserR{}
		}
		args[object.WorkflowCompletedBy] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &groupUserR{}
			}

			args[obj.WorkflowCompletedBy] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.WorkflowCompletedByUser = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.WorkflowCompletedByGroupUsers = append(foreign.R.WorkflowCompletedByGroupUsers, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.WorkflowCompletedBy == foreign.ID {
				local.R.WorkflowCompletedByUser = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.WorkflowCompletedByGroupUsers = append(foreign.R.WorkflowCompletedByGroupUsers, local)
				break
			}
		}
	}

	return nil
}

// SetGroup of the groupUser to the related item.
// Sets o.R.Group to related.
// Adds o to related.R.GroupUsers.
func (o *GroupUser) SetGroup(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Group) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"group_users\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"group_id"}),
		strmangle.WhereClause("\"", "\"", 2, groupUserPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.GroupID = related.ID
	if o.R == nil {
		o.R = &groupUserR{
			Group: related,
		}
	} else {
		o.R.Group = related
	}

	if related.R == nil {
		related.R = &groupR{
			GroupUsers: GroupUserSlice{o},
		}
	} else {
		related.R.GroupUsers = append(related.R.GroupUsers, o)
	}

	return nil
}

// SetRequester of the groupUser to the related item.
// Sets o.R.Requester to related.
// Adds o to related.R.RequesterGroupUsers.
func (o *GroupUser) SetRequester(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"group_users\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"requester_id"}),
		strmangle.WhereClause("\"", "\"", 2, groupUserPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.RequesterID = related.ID
	if o.R == nil {
		o.R = &groupUserR{
			Requester: related,
		}
	} else {
		o.R.Requester = related
	}

	if related.R == nil {
		related.R = &userR{
			RequesterGroupUsers: GroupUserSlice{o},
		}
	} else {
		related.R.RequesterGroupUsers = append(related.R.RequesterGroupUsers, o)
	}

	return nil
}

// SetUser of the groupUser to the related item.
// Sets o.R.User to related.
// Adds o to related.R.GroupUsers.
func (o *GroupUser) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"group_users\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, groupUserPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &groupUserR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			GroupUsers: GroupUserSlice{o},
		}
	} else {
		related.R.GroupUsers = append(related.R.GroupUsers, o)
	}

	return nil
}

// SetWorkflowCompletedByUser of the groupUser to the related item.
// Sets o.R.WorkflowCompletedByUser to related.
// Adds o to related.R.WorkflowCompletedByGroupUsers.
func (o *GroupUser) SetWorkflowCompletedByUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"group_users\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"workflow_completed_by"}),
		strmangle.WhereClause("\"", "\"", 2, groupUserPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.WorkflowCompletedBy = related.ID
	if o.R == nil {
		o.R = &groupUserR{
			WorkflowCompletedByUser: related,
		}
	} else {
		o.R.WorkflowCompletedByUser = related
	}

	if related.R == nil {
		related.R = &userR{
			WorkflowCompletedByGroupUsers: GroupUserSlice{o},
		}
	} else {
		related.R.WorkflowCompletedByGroupUsers = append(related.R.WorkflowCompletedByGroupUsers, o)
	}

	return nil
}

// GroupUsers retrieves all the records using an executor.
func GroupUsers(mods ...qm.QueryMod) groupUserQuery {
	mods = append(mods, qm.From("\"group_users\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"group_users\".*"})
	}

	return groupUserQuery{q}
}

// FindGroupUser retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindGroupUser(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*GroupUser, error) {
	groupUserObj := &GroupUser{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"group_users\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, groupUserObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from group_users")
	}

	if err = groupUserObj.doAfterSelectHooks(ctx, exec); err != nil {
		return groupUserObj, err
	}

	return groupUserObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *GroupUser) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no group_users provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(groupUserColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	groupUserInsertCacheMut.RLock()
	cache, cached := groupUserInsertCache[key]
	groupUserInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			groupUserAllColumns,
			groupUserColumnsWithDefault,
			groupUserColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(groupUserType, groupUserMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(groupUserType, groupUserMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"group_users\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"group_users\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into group_users")
	}

	if !cached {
		groupUserInsertCacheMut.Lock()
		groupUserInsertCache[key] = cache
		groupUserInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the GroupUser.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *GroupUser) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	groupUserUpdateCacheMut.RLock()
	cache, cached := groupUserUpdateCache[key]
	groupUserUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			groupUserAllColumns,
			groupUserPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update group_users, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"group_users\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, groupUserPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(groupUserType, groupUserMapping, append(wl, groupUserPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update group_users row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for group_users")
	}

	if !cached {
		groupUserUpdateCacheMut.Lock()
		groupUserUpdateCache[key] = cache
		groupUserUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q groupUserQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for group_users")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for group_users")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o GroupUserSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), groupUserPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"group_users\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, groupUserPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in groupUser slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all groupUser")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *GroupUser) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no group_users provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(groupUserColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	groupUserUpsertCacheMut.RLock()
	cache, cached := groupUserUpsertCache[key]
	groupUserUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			groupUserAllColumns,
			groupUserColumnsWithDefault,
			groupUserColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			groupUserAllColumns,
			groupUserPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert group_users, could not build update column list")
		}

		ret := strmangle.SetComplement(groupUserAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(groupUserPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert group_users, could not build conflict column list")
			}

			conflict = make([]string, len(groupUserPrimaryKeyColumns))
			copy(conflict, groupUserPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"group_users\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(groupUserType, groupUserMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(groupUserType, groupUserMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert group_users")
	}

	if !cached {
		groupUserUpsertCacheMut.Lock()
		groupUserUpsertCache[key] = cache
		groupUserUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single GroupUser record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *GroupUser) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no GroupUser provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), groupUserPrimaryKeyMapping)
	sql := "DELETE FROM \"group_users\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from group_users")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for group_users")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q groupUserQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no groupUserQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from group_users")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for group_users")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o GroupUserSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(groupUserBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), groupUserPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"group_users\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, groupUserPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from groupUser slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for group_users")
	}

	if len(groupUserAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *GroupUser) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindGroupUser(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *GroupUserSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := GroupUserSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), groupUserPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"group_users\".* FROM \"group_users\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, groupUserPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in GroupUserSlice")
	}

	*o = slice

	return nil
}

// GroupUserExists checks if the GroupUser row exists.
func GroupUserExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"group_users\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if group_users exists")
	}

	return exists, nil
}

// Exists checks if the GroupUser row exists.
func (o *GroupUser) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return GroupUserExists(ctx, exec, o.ID)
}
