// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: chatrooms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChatroom = `-- name: CreateChatroom :one
INSERT INTO chatrooms (
  name, workflow_state, type, created_by
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, name, workflow_state, type, created_by, created_at, updated_at, deleted_at
`

type CreateChatroomParams struct {
	Name          string
	WorkflowState ChatroomWorkflowState
	Type          ChatroomType
	CreatedBy     pgtype.UUID
}

func (q *Queries) CreateChatroom(ctx context.Context, arg CreateChatroomParams) (Chatroom, error) {
	row := q.db.QueryRow(ctx, createChatroom,
		arg.Name,
		arg.WorkflowState,
		arg.Type,
		arg.CreatedBy,
	)
	var i Chatroom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WorkflowState,
		&i.Type,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getChatroom = `-- name: GetChatroom :one
SELECT id, name, workflow_state, type, created_by, created_at, updated_at, deleted_at FROM chatrooms
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetChatroom(ctx context.Context, id pgtype.UUID) (Chatroom, error) {
	row := q.db.QueryRow(ctx, getChatroom, id)
	var i Chatroom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WorkflowState,
		&i.Type,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getChatroomCreator = `-- name: GetChatroomCreator :one
SELECT u.id, u.email, u.username, u.password, u.workflow_state, u.reset_password_url, u.created_at, u.updated_at, u.deleted_at FROM chatrooms c
JOIN users u ON c.created_by = u.id
WHERE c.id = $1 LIMIT 1
`

func (q *Queries) GetChatroomCreator(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getChatroomCreator, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.WorkflowState,
		&i.ResetPasswordUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getChatroomMessages = `-- name: GetChatroomMessages :many
SELECT m.id, m.sender_id, m.recipient_id, m.chatroom_id, m.workflow_state, m.message_type, m.content, m.is_read, m.created_at, m.updated_at, m.deleted_at from messages m
JOIN chatrooms c ON m.chatroom_id = c.id
WHERE c.id = $1
`

func (q *Queries) GetChatroomMessages(ctx context.Context, id pgtype.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, getChatroomMessages, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientID,
			&i.ChatroomID,
			&i.WorkflowState,
			&i.MessageType,
			&i.Content,
			&i.IsRead,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatroomWithCreator = `-- name: GetChatroomWithCreator :one
SELECT c.id, c.name, c.workflow_state, c.type, c.created_by, c.created_at, c.updated_at, c.deleted_at,
  u.username creator_username,
  u.email creator_email,
  u.workflow_state creator_workflow_state
FROM chatrooms c
JOIN users u ON u.id = c.created_by 
WHERE $2 = $1 LIMIT 1
`

type GetChatroomWithCreatorParams struct {
	Column1 interface{}
	ID      interface{}
}

type GetChatroomWithCreatorRow struct {
	ID                   pgtype.UUID
	Name                 string
	WorkflowState        ChatroomWorkflowState
	Type                 ChatroomType
	CreatedBy            pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
	CreatorUsername      string
	CreatorEmail         string
	CreatorWorkflowState UserWorkflowState
}

func (q *Queries) GetChatroomWithCreator(ctx context.Context, arg GetChatroomWithCreatorParams) (GetChatroomWithCreatorRow, error) {
	row := q.db.QueryRow(ctx, getChatroomWithCreator, arg.Column1, arg.ID)
	var i GetChatroomWithCreatorRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WorkflowState,
		&i.Type,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatorUsername,
		&i.CreatorEmail,
		&i.CreatorWorkflowState,
	)
	return i, err
}

const getChatrooms = `-- name: GetChatrooms :many
SELECT id, name, workflow_state, type, created_by, created_at, updated_at, deleted_at FROM chatrooms
WHERE workflow_state = ANY($1::chatroom_workflow_state[])
`

func (q *Queries) GetChatrooms(ctx context.Context, workflowStates []ChatroomWorkflowState) ([]Chatroom, error) {
	rows, err := q.db.Query(ctx, getChatrooms, workflowStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chatroom
	for rows.Next() {
		var i Chatroom
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.WorkflowState,
			&i.Type,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatroomsByCreatorID = `-- name: GetChatroomsByCreatorID :many
SELECT id, name, workflow_state, type, created_by, created_at, updated_at, deleted_at FROM chatrooms
WHERE created_by = $1
LIMIT $3
OFFSET $2
`

type GetChatroomsByCreatorIDParams struct {
	ID       pgtype.UUID
	Page     int32
	PageSize int32
}

func (q *Queries) GetChatroomsByCreatorID(ctx context.Context, arg GetChatroomsByCreatorIDParams) ([]Chatroom, error) {
	rows, err := q.db.Query(ctx, getChatroomsByCreatorID, arg.ID, arg.Page, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chatroom
	for rows.Next() {
		var i Chatroom
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.WorkflowState,
			&i.Type,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatroomsBySearchTerm = `-- name: GetChatroomsBySearchTerm :many
SELECT id, name, workflow_state, type, created_by, created_at, updated_at, deleted_at FROM chatrooms
WHERE name ILIKE $1 AND
  workflow_state = ANY($2::chatroom_workflow_state[])
`

type GetChatroomsBySearchTermParams struct {
	SearchTerm     string
	WorkflowStates []ChatroomWorkflowState
}

func (q *Queries) GetChatroomsBySearchTerm(ctx context.Context, arg GetChatroomsBySearchTermParams) ([]Chatroom, error) {
	rows, err := q.db.Query(ctx, getChatroomsBySearchTerm, arg.SearchTerm, arg.WorkflowStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chatroom
	for rows.Next() {
		var i Chatroom
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.WorkflowState,
			&i.Type,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChatroom = `-- name: UpdateChatroom :one
UPDATE chatrooms
  set name = $2,
  workflow_state = $3,
  type = $4
WHERE id = $1
RETURNING id, name, workflow_state, type, created_by, created_at, updated_at, deleted_at
`

type UpdateChatroomParams struct {
	ID            pgtype.UUID
	Name          string
	WorkflowState ChatroomWorkflowState
	Type          ChatroomType
}

func (q *Queries) UpdateChatroom(ctx context.Context, arg UpdateChatroomParams) (Chatroom, error) {
	row := q.db.QueryRow(ctx, updateChatroom,
		arg.ID,
		arg.Name,
		arg.WorkflowState,
		arg.Type,
	)
	var i Chatroom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WorkflowState,
		&i.Type,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
