// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: chatrooms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChatroom = `-- name: CreateChatroom :one
INSERT INTO chatrooms (
 id, name, workflow_state, type, created_by
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, name, workflow_state, type, created_by, created_at, updated_at, deleted_at
`

type CreateChatroomParams struct {
	ID            pgtype.UUID
	Name          string
	WorkflowState ChatroomWorkflowState
	Type          ChatroomType
	CreatedBy     pgtype.UUID
}

func (q *Queries) CreateChatroom(ctx context.Context, arg CreateChatroomParams) (Chatroom, error) {
	row := q.db.QueryRow(ctx, createChatroom,
		arg.ID,
		arg.Name,
		arg.WorkflowState,
		arg.Type,
		arg.CreatedBy,
	)
	var i Chatroom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WorkflowState,
		&i.Type,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createChatroomMessage = `-- name: CreateChatroomMessage :one
INSERT INTO messages (
 id, sender_id, chatroom_id, content, workflow_state, message_type
) VALUES (
  $1, $2, $3, $4, 'created', 'chatroom'
)
RETURNING id, sender_id, recipient_id, chatroom_id, workflow_state, message_type, content, is_read, created_at, updated_at, deleted_at
`

type CreateChatroomMessageParams struct {
	ID         pgtype.UUID
	SenderID   pgtype.UUID
	ChatroomID pgtype.UUID
	Content    string
}

func (q *Queries) CreateChatroomMessage(ctx context.Context, arg CreateChatroomMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createChatroomMessage,
		arg.ID,
		arg.SenderID,
		arg.ChatroomID,
		arg.Content,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.ChatroomID,
		&i.WorkflowState,
		&i.MessageType,
		&i.Content,
		&i.IsRead,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getChatroom = `-- name: GetChatroom :one
SELECT id, name, workflow_state, type, created_by, created_at, updated_at, deleted_at FROM chatrooms
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetChatroom(ctx context.Context, id pgtype.UUID) (Chatroom, error) {
	row := q.db.QueryRow(ctx, getChatroom, id)
	var i Chatroom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WorkflowState,
		&i.Type,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getChatroomByName = `-- name: GetChatroomByName :one
SELECT id, name, workflow_state, type, created_by, created_at, updated_at, deleted_at FROM chatrooms
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetChatroomByName(ctx context.Context, name string) (Chatroom, error) {
	row := q.db.QueryRow(ctx, getChatroomByName, name)
	var i Chatroom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WorkflowState,
		&i.Type,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getChatroomCreator = `-- name: GetChatroomCreator :one
SELECT u.id, u.email, u.username, u.password, u.workflow_state, u.reset_password_url, u.created_at, u.updated_at, u.deleted_at FROM chatrooms c
JOIN users u ON c.created_by = u.id
WHERE c.id = $1 LIMIT 1
`

func (q *Queries) GetChatroomCreator(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getChatroomCreator, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.WorkflowState,
		&i.ResetPasswordUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getChatroomMessages = `-- name: GetChatroomMessages :many
SELECT m.id, m.sender_id, m.recipient_id, m.chatroom_id, m.workflow_state, m.message_type, m.content, m.is_read, m.created_at, m.updated_at, m.deleted_at,
  c.name chatroom_name,
  c.type chatroom_type,
  c.workflow_state chatroom_workflow_state,
  c.created_by chatroom_creator_id,
  u.email sender_email,
  u.username sender_username,
  u.workflow_state sender_workflow_state
FROM messages m
JOIN chatrooms c ON m.chatroom_id = c.id
JOIN users u ON u.id = m.sender_id
WHERE c.id = $1
ORDER BY m.created_at DESC
`

type GetChatroomMessagesRow struct {
	ID                    pgtype.UUID
	SenderID              pgtype.UUID
	RecipientID           pgtype.UUID
	ChatroomID            pgtype.UUID
	WorkflowState         MessageWorkflowState
	MessageType           MessageType
	Content               string
	IsRead                pgtype.Bool
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	DeletedAt             pgtype.Timestamptz
	ChatroomName          string
	ChatroomType          ChatroomType
	ChatroomWorkflowState ChatroomWorkflowState
	ChatroomCreatorID     pgtype.UUID
	SenderEmail           string
	SenderUsername        string
	SenderWorkflowState   UserWorkflowState
}

func (q *Queries) GetChatroomMessages(ctx context.Context, id pgtype.UUID) ([]GetChatroomMessagesRow, error) {
	rows, err := q.db.Query(ctx, getChatroomMessages, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChatroomMessagesRow
	for rows.Next() {
		var i GetChatroomMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientID,
			&i.ChatroomID,
			&i.WorkflowState,
			&i.MessageType,
			&i.Content,
			&i.IsRead,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ChatroomName,
			&i.ChatroomType,
			&i.ChatroomWorkflowState,
			&i.ChatroomCreatorID,
			&i.SenderEmail,
			&i.SenderUsername,
			&i.SenderWorkflowState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatroomWithCreator = `-- name: GetChatroomWithCreator :one
SELECT c.id, c.name, c.workflow_state, c.type, c.created_by, c.created_at, c.updated_at, c.deleted_at,
  u.username creator_username,
  u.email creator_email,
  u.workflow_state creator_workflow_state
FROM chatrooms c
JOIN users u ON u.id = c.created_by 
WHERE c.id = $1 LIMIT 1
`

type GetChatroomWithCreatorRow struct {
	ID                   pgtype.UUID
	Name                 string
	WorkflowState        ChatroomWorkflowState
	Type                 ChatroomType
	CreatedBy            pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
	CreatorUsername      string
	CreatorEmail         string
	CreatorWorkflowState UserWorkflowState
}

func (q *Queries) GetChatroomWithCreator(ctx context.Context, id pgtype.UUID) (GetChatroomWithCreatorRow, error) {
	row := q.db.QueryRow(ctx, getChatroomWithCreator, id)
	var i GetChatroomWithCreatorRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WorkflowState,
		&i.Type,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatorUsername,
		&i.CreatorEmail,
		&i.CreatorWorkflowState,
	)
	return i, err
}

const getChatroomsByCreatorIDAndWorkflowStates = `-- name: GetChatroomsByCreatorIDAndWorkflowStates :many
SELECT id, name, workflow_state, type, created_by, created_at, updated_at, deleted_at FROM chatrooms
WHERE created_by = $1 AND
  workflow_state = ANY($2::chatroom_workflow_state[])
LIMIT $4
OFFSET $3
`

type GetChatroomsByCreatorIDAndWorkflowStatesParams struct {
	ID             pgtype.UUID
	WorkflowStates []ChatroomWorkflowState
	Page           int32
	PageSize       int32
}

func (q *Queries) GetChatroomsByCreatorIDAndWorkflowStates(ctx context.Context, arg GetChatroomsByCreatorIDAndWorkflowStatesParams) ([]Chatroom, error) {
	rows, err := q.db.Query(ctx, getChatroomsByCreatorIDAndWorkflowStates,
		arg.ID,
		arg.WorkflowStates,
		arg.Page,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chatroom
	for rows.Next() {
		var i Chatroom
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.WorkflowState,
			&i.Type,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatroomsBySearchTermAndWorkflowStates = `-- name: GetChatroomsBySearchTermAndWorkflowStates :many
SELECT id, name, workflow_state, type, created_by, created_at, updated_at, deleted_at FROM chatrooms
WHERE name ILIKE $1 AND
  workflow_state = ANY($2::chatroom_workflow_state[])
LIMIT $4
OFFSET $3
`

type GetChatroomsBySearchTermAndWorkflowStatesParams struct {
	SearchTerm     string
	WorkflowStates []ChatroomWorkflowState
	Page           int32
	PageSize       int32
}

func (q *Queries) GetChatroomsBySearchTermAndWorkflowStates(ctx context.Context, arg GetChatroomsBySearchTermAndWorkflowStatesParams) ([]Chatroom, error) {
	rows, err := q.db.Query(ctx, getChatroomsBySearchTermAndWorkflowStates,
		arg.SearchTerm,
		arg.WorkflowStates,
		arg.Page,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chatroom
	for rows.Next() {
		var i Chatroom
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.WorkflowState,
			&i.Type,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatroomsByWorkflowStates = `-- name: GetChatroomsByWorkflowStates :many
SELECT id, name, workflow_state, type, created_by, created_at, updated_at, deleted_at FROM chatrooms
WHERE workflow_state = ANY($1::chatroom_workflow_state[])
LIMIT $3
OFFSET $2
`

type GetChatroomsByWorkflowStatesParams struct {
	WorkflowStates []ChatroomWorkflowState
	Page           int32
	PageSize       int32
}

func (q *Queries) GetChatroomsByWorkflowStates(ctx context.Context, arg GetChatroomsByWorkflowStatesParams) ([]Chatroom, error) {
	rows, err := q.db.Query(ctx, getChatroomsByWorkflowStates, arg.WorkflowStates, arg.Page, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chatroom
	for rows.Next() {
		var i Chatroom
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.WorkflowState,
			&i.Type,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChatroom = `-- name: UpdateChatroom :one
UPDATE chatrooms
  set name = $2,
  workflow_state = $3,
  type = $4
WHERE id = $1
RETURNING id, name, workflow_state, type, created_by, created_at, updated_at, deleted_at
`

type UpdateChatroomParams struct {
	ID            pgtype.UUID
	Name          string
	WorkflowState ChatroomWorkflowState
	Type          ChatroomType
}

func (q *Queries) UpdateChatroom(ctx context.Context, arg UpdateChatroomParams) (Chatroom, error) {
	row := q.db.QueryRow(ctx, updateChatroom,
		arg.ID,
		arg.Name,
		arg.WorkflowState,
		arg.Type,
	)
	var i Chatroom
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WorkflowState,
		&i.Type,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
