// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ChatroomType string

const (
	ChatroomTypePrivate ChatroomType = "private"
	ChatroomTypePublic  ChatroomType = "public"
)

func (e *ChatroomType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChatroomType(s)
	case string:
		*e = ChatroomType(s)
	default:
		return fmt.Errorf("unsupported scan type for ChatroomType: %T", src)
	}
	return nil
}

type NullChatroomType struct {
	ChatroomType ChatroomType
	Valid        bool // Valid is true if ChatroomType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChatroomType) Scan(value interface{}) error {
	if value == nil {
		ns.ChatroomType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChatroomType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChatroomType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChatroomType), nil
}

type ChatroomWorkflowState string

const (
	ChatroomWorkflowStateActive  ChatroomWorkflowState = "active"
	ChatroomWorkflowStateDeleted ChatroomWorkflowState = "deleted"
)

func (e *ChatroomWorkflowState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChatroomWorkflowState(s)
	case string:
		*e = ChatroomWorkflowState(s)
	default:
		return fmt.Errorf("unsupported scan type for ChatroomWorkflowState: %T", src)
	}
	return nil
}

type NullChatroomWorkflowState struct {
	ChatroomWorkflowState ChatroomWorkflowState
	Valid                 bool // Valid is true if ChatroomWorkflowState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChatroomWorkflowState) Scan(value interface{}) error {
	if value == nil {
		ns.ChatroomWorkflowState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChatroomWorkflowState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChatroomWorkflowState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChatroomWorkflowState), nil
}

type FriendshipWorkflowState string

const (
	FriendshipWorkflowStatePending   FriendshipWorkflowState = "pending"
	FriendshipWorkflowStateActive    FriendshipWorkflowState = "active"
	FriendshipWorkflowStateRejected  FriendshipWorkflowState = "rejected"
	FriendshipWorkflowStateCancelled FriendshipWorkflowState = "cancelled"
	FriendshipWorkflowStateDeleted   FriendshipWorkflowState = "deleted"
)

func (e *FriendshipWorkflowState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FriendshipWorkflowState(s)
	case string:
		*e = FriendshipWorkflowState(s)
	default:
		return fmt.Errorf("unsupported scan type for FriendshipWorkflowState: %T", src)
	}
	return nil
}

type NullFriendshipWorkflowState struct {
	FriendshipWorkflowState FriendshipWorkflowState
	Valid                   bool // Valid is true if FriendshipWorkflowState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFriendshipWorkflowState) Scan(value interface{}) error {
	if value == nil {
		ns.FriendshipWorkflowState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FriendshipWorkflowState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFriendshipWorkflowState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FriendshipWorkflowState), nil
}

type MessageType string

const (
	MessageTypePrivate  MessageType = "private"
	MessageTypeChatroom MessageType = "chatroom"
)

func (e *MessageType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageType(s)
	case string:
		*e = MessageType(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageType: %T", src)
	}
	return nil
}

type NullMessageType struct {
	MessageType MessageType
	Valid       bool // Valid is true if MessageType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageType) Scan(value interface{}) error {
	if value == nil {
		ns.MessageType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageType), nil
}

type MessageWorkflowState string

const (
	MessageWorkflowStateCreated MessageWorkflowState = "created"
	MessageWorkflowStateUpdated MessageWorkflowState = "updated"
	MessageWorkflowStateDeleted MessageWorkflowState = "deleted"
)

func (e *MessageWorkflowState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageWorkflowState(s)
	case string:
		*e = MessageWorkflowState(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageWorkflowState: %T", src)
	}
	return nil
}

type NullMessageWorkflowState struct {
	MessageWorkflowState MessageWorkflowState
	Valid                bool // Valid is true if MessageWorkflowState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageWorkflowState) Scan(value interface{}) error {
	if value == nil {
		ns.MessageWorkflowState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageWorkflowState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageWorkflowState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageWorkflowState), nil
}

type UserWorkflowState string

const (
	UserWorkflowStateActive     UserWorkflowState = "active"
	UserWorkflowStateSuspended  UserWorkflowState = "suspended"
	UserWorkflowStateUnverified UserWorkflowState = "unverified"
	UserWorkflowStateDeleted    UserWorkflowState = "deleted"
)

func (e *UserWorkflowState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserWorkflowState(s)
	case string:
		*e = UserWorkflowState(s)
	default:
		return fmt.Errorf("unsupported scan type for UserWorkflowState: %T", src)
	}
	return nil
}

type NullUserWorkflowState struct {
	UserWorkflowState UserWorkflowState
	Valid             bool // Valid is true if UserWorkflowState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserWorkflowState) Scan(value interface{}) error {
	if value == nil {
		ns.UserWorkflowState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserWorkflowState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserWorkflowState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserWorkflowState), nil
}

type Chatroom struct {
	ID            pgtype.UUID
	Name          string
	WorkflowState ChatroomWorkflowState
	Type          ChatroomType
	CreatedBy     pgtype.UUID
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type Friendship struct {
	ID                  pgtype.UUID
	RequesterID         pgtype.UUID
	UserID              pgtype.UUID
	WorkflowState       FriendshipWorkflowState
	WorkflowCompletedBy pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	DeletedAt           pgtype.Timestamptz
}

type Message struct {
	ID            pgtype.UUID
	SenderID      pgtype.UUID
	RecipientID   pgtype.UUID
	ChatroomID    pgtype.UUID
	WorkflowState MessageWorkflowState
	MessageType   MessageType
	Content       string
	IsRead        pgtype.Bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
	Revoked   pgtype.Bool
}

type User struct {
	ID               pgtype.UUID
	Email            string
	Username         string
	Password         string
	WorkflowState    UserWorkflowState
	ResetPasswordUrl pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}
