// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
  user_id, token, expires_at
) VALUES (
  $1, $2, $3
)
RETURNING id, user_id, token, expires_at, created_at, revoked
`

type CreateRefreshTokenParams struct {
	UserID    pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamp
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.Token, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Revoked,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  email, username, password, workflow_state
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, email, username, password, workflow_state, reset_password_url, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email         string
	Username      string
	Password      string
	WorkflowState UserWorkflowState
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.WorkflowState,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.WorkflowState,
		&i.ResetPasswordUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFriend = `-- name: GetFriend :one
SELECT u.id, u.email, u.username, u.password, u.workflow_state, u.reset_password_url, u.created_at, u.updated_at, u.deleted_at
FROM (
  SELECT 
    CASE
      WHEN f.user_id = $1 THEN f.requester_id
      WHEN f.requester_id = $1 THEN f.user_id
    END AS id
  FROM friendships f
  WHERE f.workflow_state = 'active' AND 
        ((f.requester_id = $1 AND f.user_id = $2) OR
         (f.requester_id = $2 AND f.user_id = $1))
  LIMIT 1
) AS friends
JOIN users u ON u.id = friends.id
LIMIT 1
`

type GetFriendParams struct {
	UserID   pgtype.UUID
	FriendID pgtype.UUID
}

func (q *Queries) GetFriend(ctx context.Context, arg GetFriendParams) (User, error) {
	row := q.db.QueryRow(ctx, getFriend, arg.UserID, arg.FriendID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.WorkflowState,
		&i.ResetPasswordUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFriends = `-- name: GetFriends :many
SELECT u.id, u.email, u.username, u.password, u.workflow_state, u.reset_password_url, u.created_at, u.updated_at, u.deleted_at
FROM (
  SELECT 
    CASE
      WHEN f.user_id = $1 THEN f.requester_id
      WHEN f.requester_id = $1 THEN f.user_id
    END AS id
  FROM friendships f
  WHERE f.workflow_state = 'active' AND 
        (f.requester_id = $1 OR f.user_id = $1)
) AS friends
JOIN users u ON u.id = friends.id
LIMIT $3
OFFSET $2
`

type GetFriendsParams struct {
	ID       pgtype.UUID
	Page     int32
	PageSize int32
}

func (q *Queries) GetFriends(ctx context.Context, arg GetFriendsParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getFriends, arg.ID, arg.Page, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.Password,
			&i.WorkflowState,
			&i.ResetPasswordUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrivateConversation = `-- name: GetPrivateConversation :many
SELECT id, sender_id, recipient_id, chatroom_id, workflow_state, message_type, content, is_read, created_at, updated_at, deleted_at FROM messages m1
WHERE m1.sender_id = $3 AND m1.recipient_id = $4 
UNION
SELECT id, sender_id, recipient_id, chatroom_id, workflow_state, message_type, content, is_read, created_at, updated_at, deleted_at FROM messages m2
WHERE m2.sender_id = $4 AND m2.recipient_id = $3
ORDER BY created_at DESC
LIMIT $2
OFFSET $1
`

type GetPrivateConversationParams struct {
	Page         int32
	PageSize     int32
	FirstUserID  pgtype.UUID
	SecondUserID pgtype.UUID
}

func (q *Queries) GetPrivateConversation(ctx context.Context, arg GetPrivateConversationParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getPrivateConversation,
		arg.Page,
		arg.PageSize,
		arg.FirstUserID,
		arg.SecondUserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientID,
			&i.ChatroomID,
			&i.WorkflowState,
			&i.MessageType,
			&i.Content,
			&i.IsRead,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, email, username, password, workflow_state, reset_password_url, created_at, updated_at, deleted_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.WorkflowState,
		&i.ResetPasswordUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, password, workflow_state, reset_password_url, created_at, updated_at, deleted_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.WorkflowState,
		&i.ResetPasswordUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username, password, workflow_state, reset_password_url, created_at, updated_at, deleted_at FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.WorkflowState,
		&i.ResetPasswordUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserPassword = `-- name: GetUserPassword :one
SELECT password FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserPassword(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserPassword, id)
	var password string
	err := row.Scan(&password)
	return password, err
}
