// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
  user_id, token, expires_at
) VALUES (
  $1, $2, $3
)
RETURNING id, user_id, token, expires_at, created_at, revoked
`

type CreateRefreshTokenParams struct {
	UserID    pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamp
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.Token, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Revoked,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  email, username, password, workflow_state
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, email, username, password, workflow_state, reset_password_url, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email         string
	Username      string
	Password      string
	WorkflowState UserWorkflowState
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.WorkflowState,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.WorkflowState,
		&i.ResetPasswordUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFriend = `-- name: GetFriend :one
SELECT u.id, u.email, u.username, u.password, u.workflow_state, u.reset_password_url, u.created_at, u.updated_at, u.deleted_at
FROM (
  SELECT 
    CASE
      WHEN f.user_id = $1 THEN f.requester_id
      WHEN f.requester_id = $1 THEN f.user_id
    END AS id
  FROM friendships f
  WHERE f.workflow_state = 'active' AND 
        ((f.requester_id = $1 AND f.user_id = $2) OR
         (f.requester_id = $2 AND f.user_id = $1))
  LIMIT 1
) AS friends
JOIN users u ON u.id = friends.id
LIMIT 1
`

type GetFriendParams struct {
	UserID   pgtype.UUID
	FriendID pgtype.UUID
}

func (q *Queries) GetFriend(ctx context.Context, arg GetFriendParams) (User, error) {
	row := q.db.QueryRow(ctx, getFriend, arg.UserID, arg.FriendID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.WorkflowState,
		&i.ResetPasswordUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFriends = `-- name: GetFriends :many
SELECT u.id, u.email, u.username, u.password, u.workflow_state, u.reset_password_url, u.created_at, u.updated_at, u.deleted_at
FROM (
  SELECT 
    CASE
      WHEN f.user_id = $1 THEN f.requester_id
      WHEN f.requester_id = $1 THEN f.user_id
    END AS id
  FROM friendships f
  WHERE f.workflow_state = 'active' AND 
        (f.requester_id = $1 OR f.user_id = $1)
) AS friends
JOIN users u ON u.id = friends.id
LIMIT $3
OFFSET $2
`

type GetFriendsParams struct {
	ID       pgtype.UUID
	Page     int32
	PageSize int32
}

func (q *Queries) GetFriends(ctx context.Context, arg GetFriendsParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getFriends, arg.ID, arg.Page, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.Password,
			&i.WorkflowState,
			&i.ResetPasswordUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrivateConversation = `-- name: GetPrivateConversation :many
SELECT m.id, m.sender_id, m.recipient_id, m.chatroom_id, m.workflow_state, m.message_type, m.content, m.is_read, m.created_at, m.updated_at, m.deleted_at,
  s.username sender_username,
  s.email sender_email,
  s.workflow_state sender_workflow_state,
  r.username recipient_username,
  r.email recipient_email,
  r.workflow_state recipient_workflow_state
FROM messages m
JOIN users s ON s.id = m.sender_id
JOIN users r ON r.id = m.recipient_id
WHERE (m.sender_id = $1 AND m.recipient_id = $2)
  OR (m.sender_id = $2 AND m.recipient_id = $1)
ORDER BY m.created_at DESC
LIMIT $4
OFFSET $3
`

type GetPrivateConversationParams struct {
	FirstUserID  pgtype.UUID
	SecondUserID pgtype.UUID
	Page         int32
	PageSize     int32
}

type GetPrivateConversationRow struct {
	ID                     pgtype.UUID
	SenderID               pgtype.UUID
	RecipientID            pgtype.UUID
	ChatroomID             pgtype.UUID
	WorkflowState          MessageWorkflowState
	MessageType            MessageType
	Content                string
	IsRead                 pgtype.Bool
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	DeletedAt              pgtype.Timestamptz
	SenderUsername         string
	SenderEmail            string
	SenderWorkflowState    UserWorkflowState
	RecipientUsername      string
	RecipientEmail         string
	RecipientWorkflowState UserWorkflowState
}

func (q *Queries) GetPrivateConversation(ctx context.Context, arg GetPrivateConversationParams) ([]GetPrivateConversationRow, error) {
	rows, err := q.db.Query(ctx, getPrivateConversation,
		arg.FirstUserID,
		arg.SecondUserID,
		arg.Page,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPrivateConversationRow
	for rows.Next() {
		var i GetPrivateConversationRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientID,
			&i.ChatroomID,
			&i.WorkflowState,
			&i.MessageType,
			&i.Content,
			&i.IsRead,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SenderUsername,
			&i.SenderEmail,
			&i.SenderWorkflowState,
			&i.RecipientUsername,
			&i.RecipientEmail,
			&i.RecipientWorkflowState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, email, username, password, workflow_state, reset_password_url, created_at, updated_at, deleted_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.WorkflowState,
		&i.ResetPasswordUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, password, workflow_state, reset_password_url, created_at, updated_at, deleted_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.WorkflowState,
		&i.ResetPasswordUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username, password, workflow_state, reset_password_url, created_at, updated_at, deleted_at FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.WorkflowState,
		&i.ResetPasswordUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserPassword = `-- name: GetUserPassword :one
SELECT password FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserPassword(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserPassword, id)
	var password string
	err := row.Scan(&password)
	return password, err
}
